export const MARKETPLACE_STORAGE_STATE_ENV = {
  amazon: 'AMAZON_STORAGE_STATE_PATH',
  mercado_livre: 'MERCADO_LIVRE_STORAGE_STATE_PATH',
  shopee: 'SHOPEE_STORAGE_STATE_PATH',
} as const;

export const MERCADO_LIVRE_COOKIE_HEADER_PATH_ENV =
  'MERCADO_LIVRE_COOKIE_HEADER_PATH';

export const MERCADO_LIVRE_COOKIE_HEADER_ENV = 'MERCADO_LIVRE_COOKIE_HEADER';
